### ISSUE TITLE
Adding translation to portuguese in documentation

### ISSUE THREAD

**Issue by Marco4325** [ihategfw/teletrans#1]
I've been looking for a project to start making a documentation in portuguese, so I've found this repository and I had a interest on working with it.

Is there any chance to contribuite it with a portuguese documentation?

**Comment by ihategfw** [comment]
What is your demand actually? It seems like this repository might not be able to meet your needs.

**Comment by luiz-otavio** [comment]
> What is your demand actually? It seems like this repository might not be able to meet your needs.

What do you mean about "meeting your needs"?

**Comment by ihategfw** [comment]
> > What is your demand actually? It seems like this repository might not be able to meet your needs.
> 
> What do you mean about "meeting your needs"?

Because I don't know what he wants. It seems like he wants to translate documents and needs "Google Translate" or something like that.

**Comment by luiz-otavio** [comment]
> > > What is your demand actually? It seems like this repository might not be able to meet your needs.
> > 
> > 
> > What do you mean about "meeting your needs"?
> 
> Because I don't know what he wants. It seems like he wants to translate documents and needs "Google Translate" or something like that.

Oh yeah, sorry for the mistake of meaning.

In fact, @Marco4325 is looking for a project to translate anything to portuguese, such as making an alternative markdown for `README.md` like `README_ptBR.md`. This would be great since he wants to do that for learning purposes.
