### ISSUE TITLE
搭配 deepseek 用似乎无法中译英

### ISSUE THREAD

**Issue by love4taylor** [ihategfw/teletrans#4]
```
.tt-once,zh,zh|en 不过我们这边异地首办应该是可以的，我同学都办过
```

```
2024-05-29 13:19:46,152 - INFO - 翻译消息: 不过我们这边异地首办应该是可以的，我同学都办过
2024-05-29 13:19:48,365 - INFO - 翻译从 zh 至 en 耗时: 2.211108922958374
2024-05-29 13:19:48,366 - INFO - 翻译耗时: 2.2134783267974854
```

结果是原文返回，没有成功翻译到英文

<img width="421" alt="image" src="https://github.com/ihategfw/teletrans/assets/6081912/7b202256-f941-42c9-8b83-1336c9cc75bf">

<img width="611" alt="image" src="https://github.com/ihategfw/teletrans/assets/6081912/4b41af31-a257-4ae4-8a4b-7fc85ea9fd34">

**Comment by ihategfw** [comment]
是当时接口的问题吗？我试了一下可以正常翻译欸
```
2024-05-29 13:19:46,152 - INFO - 翻译消息: 不过我们这边异地首办应该是可以的，我同学都办过
2024-05-29 13:19:48,365 - INFO - 翻译从 zh 至 en 耗时: 2.211108922958374
2024-05-29 13:19:48,366 - INFO - 翻译耗时: 2.2134783267974854
```
<img width="357" alt="image" src="https://github.com/ihategfw/teletrans/assets/131764215/eee274be-5a97-40a6-99f0-6a6b59694725">

**Comment by love4taylor** [comment]
怪了，即使现在也不行。

```
~ love4taylor@sony-nuro-n1.love4taylor.com
❯ sudo cat /var/lib/docker/volumes/teletrans_love4taylor/_data/config.json
{
  "api_id": "******",
  "api_hash": "*******",
  "target_config": {},
  "openai": {
    "enable": true,
    "api_key": "sk-*******",
    "url": "https://api.deepseek.com/chat/completions",
    "model": "deepseek-chat"
  }
}
```

镜像版本是 `ghcr.io/ihategfw/teletrans:latest@sha256:ece6fb46ab4bb54e553273b7a4b75963312efdd5a9d23cd4ac416d810f4b9b2d`

**Comment by ihategfw** [comment]
啊原来你说的是 deepseek 啊，我会错意了
我倾向于认为是因为 deepseek-chat 这个模型比较笨，不能理解 prompt 或者说你的句子的意思
在代码里 hard code 了一句 prompt，我测试了 gpt-3.5 / gpt-4 都能正确翻译你的句子
`
If my text cannot be translated or contains nonsencial content, just repeat my words precisely. As an American English expert, you\'ll help users express themselves clearly. You\'re not just translating, but rephrasing to maintain clarity. Use plain English and common idioms, and vary sentence lengths for natural flow. Avoid regional expressions. Respond with the translated sentence.
`
或许我应该把这句 prompt 也放到配置文件里

**Comment by love4taylor** [comment]
改了下 py，把 prompt 以中文表述喂给 deepseek 就能翻译了。如果您要移到配置文件的话，麻烦顺便给温度也移过去吧。另外好奇，只有目的语言是 en 才用 openai 是因为它中译英很差？

```
    payload = {
        'messages': [
            {
            'role': 'system',
            'content':'如果我的文本无法翻译或包含无意义内容，请准确重复我的话。作为美式英语专家，您将帮助用户清晰表达自己。您不仅仅是翻译，而是重新表述以保持清晰度。使用简单英语和
常用习语，并变化句子长度以实现自然流畅。避免使用地区性表达。请回复已翻译的句子。'
            },
            {
            'role': 'user',
            'content': text,
            }
        ],
        'stream': False,
        'model': openai_model,
        'temperature': 1.1,
        'presence_penalty': 0,
        'frequency_penalty': 0,
        'top_p': 1
    }
```

<img width="522" alt="image" src="https://github.com/ihategfw/teletrans/assets/6081912/24916853-f0cd-4c52-b6f6-e372af8a282a">

**Comment by ihategfw** [comment]
> 另外好奇，只有目的语言是 en 才用 openai 是因为它中译英很差？

因为我只有这个使用场景😂，设计的时候没有考虑很周到。
同时考虑到不同的目标语言可能需要不同的 prompt ，不知道你有没有什么想法？
